#!/bin/bash


set -o errexit

set -o pipefail

set -o nounset

postgres_ready() {
    python  << END
import sys
import psycopg2
try:
    conn = psycopg2.connect(
        dbname="${POSTGRES_DB}",
        user="${POSTGRES_USER}",
        password="${POSTGRES_PASSWORD}",
        host="${POSTGRES_HOST}",
        port="${POSTGRES_PORT}"
    )
    conn.close()
    sys.exit(0)
except psycopg2.OperationalError:
    sys.exit(-1)
END
}

until postgres_ready; do
    >&2 echo "Postgres is unavailable - sleeping"
    sleep 1
done
>&2 echo "Postgres is up - continuing"

exec "$@"
