# Generated by Django 5.2.1 on 2025-07-25 18:50

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enquiries", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enquiry",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="+25180808080",
                max_length=30,
                region=None,
                verbose_name="Phone Number",
            ),
        ),
    ]
