# Generated by Django 5.2.1 on 2025-05-31 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="property",
            old_name="bedooms",
            new_name="bedrooms",
        ),
    ]
