# Generated by Django 5.2.1 on 2025-07-25 18:50

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=30, region=None, verbose_name="Phone Number"
            ),
        ),
    ]
